### PR TITLE
Zon 5752 get rid of zodb3

### PR DESCRIPTION
**Pull request by thomasbaumann**
tox -e [py27|py3] lief durch.

### CODE REVIEW

**Comment by icemac** [comment]
@thomasbaumann Sorry for not being fast enough to look at this PR. What do you think could be the next steps as the source repository seems to be deleted and there are conflicting files.

**Comment by icemac** [comment]
@mstoltenburg @thomasbaumann What do you think how we can make progress with this PR?

**Comment by icemac** [comment]
Merged to master via the command line instructions provided by GitHub.
Thank you.

**Comment by thomasbaumann** [comment]
Hi @icemac, 

sry for not reacting until now. I was confused about the notifications. I thing I created a branch from here an thoght to be in a zeitonline context while pushing :) I hope everything is fine now. Our (zeitonline) ticket is closed ;)

Best regards
Thomas.

**Comment by icemac** [comment]
@thomasbaumann I think everything is fine now. Do you need a release of the package?

**Comment by icemac** [comment]
I just released https://pypi.org/project/gocept.runner/2.2/ including this PR.

**Pull request closed without merging**
